### ISSUE TITLE
Stderr: VBoxManage: error: Missing argument to '--name'

### ISSUE THREAD

**Issue by avizuber-zz** [kapitchi/project-template-zf2-angularjs#6]
Thanks for putting this together.

I'm getting the following error:

vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["sharedfolder", "add", "572a2bd7-a18c-486c-9c33-ccf73e6dcf4c", "--name", "", "--hostpath", "/Users/Avi/Desktop/rungsvp/myapp"]

Stderr: VBoxManage: error: Missing argument to '--name'

**Comment by matuszeman** [comment]
@avizuber Hi. What's your vbox version?
TBH I'm not an expert in vbox but I tried to test this on ubuntu, win8, osx before and it was running OK.
Have you managed to fix this? If so please consider PR.

**Comment by matuszeman** [comment]
@avizuber Hey -- I updated a project. Could you try again please? Make sure you have Vagrant >= 1.6.
I amended a readme file. URLs have changed.

**Comment by avizuber-zz** [comment]
Hey @matuszeman sorry for the late reply. Just tried again and got much further this time. So this issue seems resolved.
I ran into a few other errors, but I think it's because I don't have bower or compass installed in this VM. I'll investigate more and let you know (by posting them as additional issues.) Thanks!!
